kind: Deployment
metadata:
  name: flask-test-app
spec:
  selector:
    matchLabels:
      app: flask-test-app
  replicas: 5
  template:
    metadata:
      labels:
	app: flask-test-app
    spec:
      containers:
        - name: flask-test-app
          image: docker.io/chococandy/minikube-flask-app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
